spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
    url: jdbc:mariadb://localhost:3306/security

jwt:
  secret: fsdfsdgdkflgmdsfgdfgfdghfgdthjhfghjfsklfdgmdfklmfdgkdsfsd
  token-validity-in-seconds: 60000
